---
# tasks file for syft | EL Family

- name: EL Family | Downloading and installing {{ syft_app }} {{ syft_version }}
  yum:
    name: "{{ syft_el_url }}"
    state: "{{ syft_desired_state }}"
    disable_gpg_check: yes
