---
# tasks file for syft

- name: Import install_debian.yml if OS family is Debian
  ansible.builtin.import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Import install_el.yml if OS family is EL
  ansible.builtin.import_tasks: install_el.yml
  when: ansible_os_family == "RedHat"
